game:
  socket:
    port: 8089
    protocol-version: 100101
    open-gm: true
  resource:
    resource-scanner-path: com.lzh.game
  repository:
      clear-redis-after-close: false
spring:
  data:
    mongodb:
      host: 127.0.0.1
      database: game
      port: 17217
    redisson:
      config: classpath:redisson.yml